export const AUTH_ACTIONS = {
  // Signup
  SIGNUP_USER_LOADING: "SIGNUP_USER_LOADING",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_ERROR: "SIGNUP_USER_ERROR",

  // Login
  LOGIN_USER_LOADING: "LOGIN_USER_LOADING",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",

  // Logout
  LOGOUT_USER_LOADING: "LOGOUT_USER_LOADING",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR",

  // Get Me
  GET_ME_LOADING: "GET_ME_LOADING",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",
  GET_ME_ERROR: "GET_ME_ERROR",
};
